// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VocalSurvey.Core.Skill.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CountryAndPostalCode
    {
        /// <summary>
        /// Initializes a new instance of the CountryAndPostalCode class.
        /// </summary>
        public CountryAndPostalCode()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CountryAndPostalCode class.
        /// </summary>
        public CountryAndPostalCode(string countryCode = default(string), string postalCode = default(string))
        {
            CountryCode = countryCode;
            PostalCode = postalCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryCode")]
        public string CountryCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postalCode")]
        public string PostalCode { get; set; }

    }
}
