// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WattTime.Agent.Services.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Index
    {
        /// <summary>
        /// Initializes a new instance of the Index class.
        /// </summary>
        public Index()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Index class.
        /// </summary>
        public Index(string ba = default(string), int? validFor = default(int?), System.DateTime? validUntil = default(System.DateTime?), string rating = default(string), string switchProperty = default(string), string percent = default(string), string freq = default(string), string market = default(string))
        {
            Ba = ba;
            ValidFor = validFor;
            ValidUntil = validUntil;
            Rating = rating;
            SwitchProperty = switchProperty;
            Percent = percent;
            Freq = freq;
            Market = market;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ba")]
        public string Ba { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "validFor")]
        public int? ValidFor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "validUntil")]
        public System.DateTime? ValidUntil { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rating")]
        public string Rating { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "switch")]
        public string SwitchProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "percent")]
        public string Percent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "freq")]
        public string Freq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "market")]
        public string Market { get; set; }

    }
}
