// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WattTime.Agent.Services.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Token
    {
        /// <summary>
        /// Initializes a new instance of the Token class.
        /// </summary>
        public Token()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Token class.
        /// </summary>
        public Token(string tokenProperty = default(string))
        {
            TokenProperty = tokenProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string TokenProperty { get; set; }

    }
}
