// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VocalSurvey.Core.Skill
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SkillAddressInformationClient.
    /// </summary>
    public static partial class SkillAddressInformationClientExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='deviceId'>
            /// </param>
            public static CountryAndPostalCode GetCountryAndPostalCode(this ISkillAddressInformationClient operations, string deviceId)
            {
                return operations.GetCountryAndPostalCodeAsync(deviceId).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='deviceId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CountryAndPostalCode> GetCountryAndPostalCodeAsync(this ISkillAddressInformationClient operations, string deviceId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCountryAndPostalCodeWithHttpMessagesAsync(deviceId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
